services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - ipsc-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ipsc_prod
      MYSQL_USER: ipsc_user
      MYSQL_PASSWORD: prod_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-prod-data:/var/lib/mysql
    networks:
      - ipsc-network

  redis:
    image: redis:7.0
    volumes:
      - redis-prod-data:/data
    networks:
      - ipsc-network

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - ipsc-network

networks:
  ipsc-network:
    driver: bridge

volumes:
  mysql-prod-data:
  redis-prod-data: