services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - ipsc-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ipsc_dev
      MYSQL_USER: ipsc_user
      MYSQL_PASSWORD: dev_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ipsc-network

  redis:
    image: redis:7.0
    volumes:
      - redis-data:/data
    networks:
      - ipsc-network

networks:
  ipsc-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: